# Generated by Django 3.2.7 on 2021-10-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='secao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
