# Generated by Django 3.2.7 on 2021-10-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_edicao_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='quantidadeAcao',
            field=models.IntegerField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='quantidadeTotal',
            field=models.IntegerField(blank=True, max_length=11),
        ),
    ]
