# Generated by Django 3.2.7 on 2021-10-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_usuario_primeir_acesso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='primeir_acesso',
            new_name='primeiro_acesso',
        ),
    ]
