# Generated by Django 3.2.7 on 2021-11-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_rename_primeir_acesso_usuario_primeiro_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_guerra',
            field=models.CharField(max_length=255),
        ),
    ]
